### ISSUE TITLE
Evaluation Problem

### ISSUE THREAD

**Issue by Shea192** [lizhaoliu-Lec/DENet#2]
Thanks for releasing the code. It is an impressive work.  And when I look into the whole pipeline, it is a little confused that the mIOU seems  averaged on all class? Do you change the `maximum_num_classes` during testing?

**Comment by lizhaoliu-Lec** [comment]
The evaluation metric is written to well handle the base / novel classes during training / testing.
maximum_num_classes is not changed during the training or testing for a dataset.
