### ISSUE TITLE
about dateset in config file

### ISSUE THREAD

**Issue by 1160300918** [lizhaoliu-Lec/DENet#4]
after run the function `run_VOCSBDSegmentation5i_from_scratch()` and copy the content in `train_config_denet.template` to `train_config.yml`, when I use "python -u train.py", the error is can't find "WrappedVOCSBDSegmentation5i" which in the config file, but the dataset VOC didn't contain the "WrappedVOCSBDSegmentation5i" after run the function `run_VOCSBDSegmentation5i_from_scratch()`, so where should I find the "WrappedVOCSBDSegmentation5i" folder? I tried to run other test functions in voc_sbd.py, but I didn't get what I want.

**Comment by lizhaoliu-Lec** [comment]
Sorry for the late reply. 
As set in the dataset/voc_sbd.py line 676, the dataset should be located in 
===> ROOT = '/path/to/data'
===> roots_path = os.path.join(ROOT, 'VOC').
After the preprocessing, the final folder structure should be as follow:
![image](https://user-images.githubusercontent.com/38394970/111859199-08b49580-897a-11eb-950a-891f77b5b583.png)
where the images and labels pair for the few-shot setting should be in the item_with_class folder.
If you still have trouble doing the preprocessing part, please further contact me and I will upload the dataset to dropbox or google drive for you.

**Comment by lizhaoliu-Lec** [comment]
@1160300918 I have uploaded the preprocessed voc5i dataset to google drive. The file size is about 6.4GB.
Link is as follow: https://drive.google.com/uc?export=download&id=1uWNPSd_tEG5-WCRcG1sk9-5R0yI-O0XL
