### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by Yinan-Zhao** [lizhaoliu-Lec/DENet#5]
Would you mind releasing the pretrained models on COCO-20i?

**Comment by lizhaoliu-Lec** [comment]
Sorry for the late reply, the pretrained models are lost since the latest servers upgrade.
But don't worry about it, I am currently rerunning these experiments.
The final logs of tensorboard, the pretrained models and the training protocols will be released in several days.

**Comment by lizhaoliu-Lec** [comment]
Hi, the pre-trained models are uploaded. Please refer to the readme for more details.
