### ISSUE TITLE
Cannot download PASCAL VOC 5i from your link.

### ISSUE THREAD

**Issue by zhiheLu** [lizhaoliu-Lec/DENet#7]
Could you please share a new link for downloading this dataset? Thanks.

**Comment by lizhaoliu-Lec** [comment]
It is available to me. Have you tried to turn on a VPN?
![image](https://user-images.githubusercontent.com/38394970/111983528-30a42480-8b45-11eb-951c-883d883cb854.png)

**Comment by zhiheLu** [comment]
Yeah, I am using the network in a foreign country. Anyway, I will try the other way.
