### ISSUE TITLE
Drive links are not shared?

### ISSUE THREAD

**Issue by jaymefosa** [lizhaoliu-Lec/DENet#9]
The two links on the main page both give a 404

![image](https://user-images.githubusercontent.com/92468/116400731-553a9d00-a865-11eb-98bf-de6a956af748.png)

**Comment by lizhaoliu-Lec** [comment]
![image](https://user-images.githubusercontent.com/38394970/116400909-30422c00-a85d-11eb-8de5-40a0fc920baf.png)
![image](https://user-images.githubusercontent.com/38394970/116400928-346e4980-a85d-11eb-81dc-1c197cd0af37.png)
Maybe you should try to turn on a vpn

**Comment by lizhaoliu-Lec** [comment]
> The two links on the main page both give a 404
> 
> ![image](https://user-images.githubusercontent.com/92468/116400731-553a9d00-a865-11eb-98bf-de6a956af748.png)

 It seems that the original links are only visible to me. I have changed the permission, feel free to try again!

**Comment by jaymefosa** [comment]
ah! They are working now, many thanks!
